export const AUTH_USER = "auth_user"
export const AUTH_ERROR = "auth_error"
export const FETCH_CONTENT = "fetch_content"
export const FETCH_ERROR="fetch_error"
export const BLOG_POST = "blog_post"
export const BLOG_POST_ERROR="blog_post_error"